### ISSUE TITLE
OpenCV not installable from the contribution manager in Processing 3.0

### ISSUE THREAD

**Issue by kasperkamperman** [atduskgreg/opencv-processing#87]
I run into different issues with Processing 3.0 and installing the library from the contribution manager. 
I had a student where the library was greyed-out in the 3.0a5 version and in 3.0a10 it said it was incompatible. 

![screen shot 2015-09-29 at 11 34 27](https://cloud.githubusercontent.com/assets/1760616/10161062/c255330c-66a1-11e5-9f73-619b24b9c77d.png)

I have it myself successfully running since a long time. So I decided removing the library from my libraries folder. After restarting the contribution manager says that it's already installed, however it can't be found (which is true since I removed it). 

<img width="815" alt="screen shot 2015-09-29 at 12 01 27" src="https://cloud.githubusercontent.com/assets/1760616/10161076/d8da079c-66a1-11e5-88de-f5b9010bb557.png">

The only solution for me and the students working in Processing 3.0b7 was installing the library manually.

**Comment by kasperkamperman** [comment]
Could you please update the library to Processing 3.0. 

It says that it's not compatible (some examples are indeed not because of the changed size() tag) in the contribution manager (which students use). However when I manually put the folder into the library the library just works.

**Comment by loserr1235** [comment]
I can't run the example even I have put the folder
![1](https://cloud.githubusercontent.com/assets/13272256/10261719/ed80a26c-69d7-11e5-84a7-ca97d0f7f7ba.jpg)
![2](https://cloud.githubusercontent.com/assets/13272256/10261720/f3396e6e-69d7-11e5-9499-311fde1cc11d.jpg)

**Comment by victorloux** [comment]
I got the same error as @loserr1235 (`The package “gab” does not exist. You might be missing a library.`). The issue seemed to be that I cloned the git repository in my libraries folder, but the files in the repo are organised differently from the file distributed in [Releases](https://github.com/atduskgreg/opencv-processing/releases), which seems to work. So try just downloading that instead.

Another possible option to get it installed is to open Processing 2.x (which you obviously backed up before installing 3.x :wink:) , install the OpenCV library from the contribution manager, and then it should be available in Processing 3 as well.

Once installed I had no issue using it. As mentioned before, some examples are broken because of the changed `size()` function, and you may need to re-install the Video library (as it's not included by default anymore), but the library itself seems to be compatible.

**Comment by koghe** [comment]
Hi
i'm on linux 15.04 ubuntu, java version "1.6.0_36", Processing 3.0.1, opencv release
OpenJDK Runtime Environment (IcedTea6 1.13.8) (6b36-1.13.8-0ubuntu1~15.04.1)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)
Had the same problem 
My processing 3 was configured to use the /home/user/Processing3/ folder i don't have a /home/user/processing/ folder in my home.
The only way to have the libraries enabled in the Lib Manager was to use the folder /home/user/processing/, now i can use all the example skecth. 
This can be my environment but if you have problem installing opencv on linux
try with the default processing folder.

**Comment by MagFer** [comment]
Hi!
Instead of put manually the lib into folder, the Processing 3 contribution manager doesn't detect that is installed. Some idea about what could be happening 😅?
Thank you!
<img width="812" alt="captura de pantalla 2015-11-19 a las 14 36 12" src="https://cloud.githubusercontent.com/assets/9061996/11272193/6811fb08-8ecb-11e5-9c6c-252ba4af779c.png">

**Comment by MagFer** [comment]
@loserr1235 it's important to have configured both Processing 2 & 3 the same sketchbook at the moment of download the OpenCV lib via Processing 2.
<img width="607" alt="captura de pantalla 2015-11-19 a las 14 50 06" src="https://cloud.githubusercontent.com/assets/9061996/11272447/4ea25ac6-8ecd-11e5-87db-f289dbb562ec.png">

**Comment by REAS** [comment]
This is fixed now. It was removed because many of the examples weren't compatible with the Processing 3.0 size() function, but I added it back today. I hope to modify the examples and get them updated through @atduskgreg

**Comment by FrankOcean11** [comment]
im on opencv 3 and OpenCV for Processing 0.5.2 is not available or any other opencv

**Comment by theantonius** [comment]
I had to update the examples for Processing 3.0.2 on this fork because I'm teaching this tomorrow: https://github.com/theantonius/opencv-processing

**Comment by FrankOcean11** [comment]
thanks !

**Comment by atduskgreg** [comment]
closed as of 21135f2e632838381898535cfd06f0243e4c186e and release 0.5.4
